language: generic
os: linux

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
    - ROSWELL_VERSION=19.12.13.103
    - ROSWELL_URL="https://raw.githubusercontent.com/roswell/roswell/v$ROSWELL_VERSION/scripts/install-for-ci.sh"

jobs:
  include:
    - os: linux
      env:
        - LISP=sbcl/2.0.0
        - DEST=plan-rss-linux
    - os: osx
      env:
        - LISP=sbcl/1.5.8
        - DEST=plan-rss-osx
    - os: windows
      language: shell
      env:
        - LISP=sbcl-bin/2.0.0
        - DEST=plan-rss.exe

install:
  - curl -L $ROSWELL_URL | sh
  - |
    if [ "$TRAVIS_OS_NAME" = "windows" ]; then
      choco install make
    fi

script:
  - make binary-ros
  - bin/plan-rss --version

before_deploy:
  - mv bin/plan-rss bin/$DEST

deploy:
  provider: releases
  token:
    secure: V5woEUHe2TN6pVMMWLcSWfdTn79cNoG2wtT8qChw/pV9+KAUcXNyXFPchqlnGaoWPNoMMdwehcTCJJz7MISnWO6DlepTf4KIpa42zOw6e1rwrHQ0yCGNT5KJrbfZznoYxU6M3qYXADhQKd4qft0haHiRQPUMYiTr+Qj/p1rfmCVtM+eK8yK/ASEH8yMJBhBLF/MHySLiM+zjm7LgGKtL6jT6vdcFFGH76zCaQgCunW1RXRO6If94PyGEUT13baL7tLqJntIfaQAOpozsO1NT2X8zzkekwyiuPdVZ9wQbHOsrh9bnf4PSMYcNUpmPOmNvn8rWxemsViEzd7wJTV0hL0xh2Rw/RWEbjpmiAYDFvAzeJxizk7fEExmHmjgOLJ8hY3RfpjyZronQDGwNjK47+Kw5AqA/If5xd72GMlFimm24MQmvatAEzT5aR/AteQXu2/lfcT/HxuczpQatugZNYxy1yGkKFyLSeItlhNoqWvMzNV5wh+oZCL+2wc+2vgeYEzZpuwHAfDFgerBrPljGmfjdr7ITx00QhTTUwbSXM/WqV7AVnFjobXvpMfZWCCoeEUp0IzaIR5v07+xe1qUdGxSBcR2AZJbMOFLecOm9tMxyCuEgHWscIhcQdaYVkXYqiuwj8YPHLEArRIK8eY0jsXRFmGzF435jg5Qpp63kbpc=
  cleanup: false
  file: bin/$DEST
  on:
    repo: iamFIREcracker/plan-rss
    tags: true
